/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import dto.Registro;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import logica.LogicaRegistro;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;


/**
 *
 * @author Juanma
 */
public class CiudadFecha extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CiudadFecha.class.getName());

    /**
     * Creates new form CiudadFecha
     */
    public CiudadFecha(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //Desactivamos el botón "Registrar" por defecto
        jButtonRegistrarCiudad.setEnabled(false);
        // Creamos el grupo de validación del ValidationPanel
        ValidationGroup group = validationPanelCiudad.getValidationGroup();
        
        // Ciudad no vacía y solo letras y espacios
        group.add(jTextFieldCiudad,
        StringValidators.REQUIRE_NON_EMPTY_STRING,
        StringValidators.regexp("^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$", "Solo se permiten letras y espacios", true));
        
        // Activar o desactivar el botón según la validez
        validationPanelCiudad.addChangeListener(e -> {
        jButtonRegistrarCiudad.setEnabled(validationPanelCiudad.getProblem() == null);
        });
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jDateChooserFecha = new com.toedter.calendar.JDateChooser();
        jTextFieldCiudad = new javax.swing.JTextField();
        jButtonRegistrarCiudad = new javax.swing.JButton();
        validationPanelCiudad = new org.netbeans.validation.api.ui.swing.ValidationPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Fecha de visita prevista:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 102, 11, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel1.setText("Nombre de la ciudad a visitar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 102, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 37;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 18, 11, 85);
        jPanel1.add(jDateChooserFecha, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 18, 0, 85);
        jPanel1.add(jTextFieldCiudad, gridBagConstraints);

        jButtonRegistrarCiudad.setText("Registrar");
        jButtonRegistrarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarCiudadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(423, 423, 423)
                        .addComponent(jButtonRegistrarCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(validationPanelCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(validationPanelCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(93, 93, 93)
                .addComponent(jButtonRegistrarCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private String obtenerEstacion(Date fecha) {
    SimpleDateFormat sdf = new SimpleDateFormat("MM-dd");
    String md = sdf.format(fecha);

    if (md.compareTo("03-21") >= 0 && md.compareTo("06-20") <= 0)
        return "Primavera";
    else if (md.compareTo("06-21") >= 0 && md.compareTo("09-22") <= 0)
        return "Verano";
    else if (md.compareTo("09-23") >= 0 && md.compareTo("12-20") <= 0)
        return "Otoño";
    else
        return "Invierno";
}

    
    private void jButtonRegistrarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarCiudadActionPerformed
          String ciudad = jTextFieldCiudad.getText();
          Date fecha = jDateChooserFecha.getDate();

        if (fecha == null) {
            JOptionPane.showMessageDialog(this, "Selecciona una fecha.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Determinar estación
        String estacion = obtenerEstacion(fecha);

        // Crear registro con ciudad + fecha + estación
        Registro r = new Registro(ciudad, fecha, estacion);

        LogicaRegistro.añadirRegistro(r);

        // Actualizar tabla
        ((PlanificadorViajes)getParent()).refrescarTabla();

        // Actualizar imagen
        ((PlanificadorViajes)getParent()).actualizarImagenEstacion(estacion);

        this.dispose();
    }//GEN-LAST:event_jButtonRegistrarCiudadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                CiudadFecha dialog = new CiudadFecha(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistrarCiudad;
    private com.toedter.calendar.JDateChooser jDateChooserFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCiudad;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanelCiudad;
    // End of variables declaration//GEN-END:variables
}
