/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dto.Registro;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import logica.LogicaRegistro;

/**
 *
 * @author Juanma
 */
public class PlanificadorViajes extends javax.swing.JFrame {
    
    private Ayuda ayuda;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PlanificadorViajes.class.getName());

    /**
     * Creates new form PlanificadorViajes
     */
    public PlanificadorViajes() {
        initComponents();
        
        //Modificacion de icono
        setIconImage(new ImageIcon(getClass().getResource("/img/icono_lapiz.jpg")).getImage());
        
        //Listado para Look & Feel
        DefaultComboBoxModel<String> dcm = new DefaultComboBoxModel<>();
        for (UIManager.LookAndFeelInfo lfi : UIManager.getInstalledLookAndFeels()){
            dcm.addElement(lfi.getName());
        }
        jComboBox1.setModel(dcm);
        
        ayuda = new Ayuda();
    }
    
    public void refrescarTabla(){
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yy");
        
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"Ciudad a visitar", "Fecha de visita prevista",
                                              "Estacion del año","Temperatura mínima prevista en ºC",
                                              "Temperatura máxima prevista en ºC", "Temperatura promedio"});
        
        List<Registro> listaRegistros = LogicaRegistro.getRegistro();
            for (Registro registro: listaRegistros){
                dtm.addRow(new Object[]{
                registro.getCiudad(),
                sdf.format(registro.getFechaVisita()),
                registro.getEstacion(),
                registro.getTempMin(),
                registro.getTempMax(),
                registro.getTempProm()});
        }
        // **PASO 1:** Establece el nuevo modelo (con datos)
        jTableRegistros.setModel(dtm);
        
        // **PASO 2:** Aplicar el sorter al NUEVO modelo que acabas de establecer
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(jTableRegistros.getModel());
        jTableRegistros.setRowSorter(sorter);
        
        // **PASO 3:** Definir que la columna 5 (Temperatura promedio) es numérica
        sorter.setComparator(5, (o1, o2) -> {
        Double d1 = Double.parseDouble(o1.toString());
        Double d2 = Double.parseDouble(o2.toString());
        return d1.compareTo(d2);
        });
        
        // **PASO 4:** Ordenar automáticamente de MAYOR a MENOR
        sorter.setSortKeys(
        java.util.Arrays.asList(
        new javax.swing.RowSorter.SortKey(5, javax.swing.SortOrder.DESCENDING)
            )
        );
        
        // El repaint no es estrictamente necesario, pero no estorba.
        jTableRegistros.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRegistros = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButtonEliminar = new javax.swing.JButton();
        jLabelImagen = new javax.swing.JLabel();
        jButtonAyuda = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCiudad = new javax.swing.JMenuItem();
        jMenuItemTemperatura = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Ciudad a visitar", "Fecha de visita prevista", "Estacion del año", "Temperatura minima", "Temperatura maxima", "Temperatura promedio"
            }
        ));
        jScrollPane1.setViewportView(jTableRegistros);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jButtonEliminar.setText("Eliminar visita");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 55, 0, 0);
        jPanel2.add(jButtonEliminar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 156;
        gridBagConstraints.ipady = 41;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 107, 0, 25);
        jPanel2.add(jLabelImagen, gridBagConstraints);

        jButtonAyuda.setText("Ayuda");
        jButtonAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAyudaActionPerformed(evt);
            }
        });

        jMenu1.setText("Ciudad y Temperatura");

        jMenuItemCiudad.setText("Registrar ciudad y fecha");
        jMenuItemCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCiudadActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCiudad);

        jMenuItemTemperatura.setText("Registrar temperaturas");
        jMenuItemTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTemperaturaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemTemperatura);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jComboBox1, 0, 73, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAyuda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jComboBox1)
                .addGap(235, 235, 235))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAyuda)
                        .addGap(16, 16, 16))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void actualizarImagenEstacion(String estacion) {
    switch (estacion) {
        case "Primavera":
            jLabelImagen.setIcon(escalarImagen("/img/primavera.jpg", 200, 150));
            break;

        case "Verano":
            jLabelImagen.setIcon(escalarImagen("/img/verano.jpg", 200, 150));
            break;

        case "Otoño":
            jLabelImagen.setIcon(escalarImagen("/img/otono.jpg", 200, 150));
            break;

        case "Invierno":
            jLabelImagen.setIcon(escalarImagen("/img/invierno.jpg", 200, 150));
            break;

        default:
            jLabelImagen.setIcon(null);
    }
    }
    
    private ImageIcon escalarImagen(String ruta, int ancho, int alto) {
    ImageIcon icon = new ImageIcon(getClass().getResource(ruta));
    Image img = icon.getImage();
    Image imgEscalada = img.getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
    return new ImageIcon(imgEscalada);
}


    private void jMenuItemCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCiudadActionPerformed
        CiudadFecha dialogo = new CiudadFecha(this, true);
        dialogo.setVisible(true);
    }//GEN-LAST:event_jMenuItemCiudadActionPerformed

    private void jMenuItemTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTemperaturaActionPerformed
        RegistroTemperaturas dialogo = new RegistroTemperaturas(this, true);
        dialogo.setVisible(true);
    }//GEN-LAST:event_jMenuItemTemperaturaActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
    while(true){    
        Date estacion;
        String ciudadStr = JOptionPane.showInputDialog(this,
        "Introduce la ciudad de la visita que deseas eliminar:",
        "Eliminación de visita",JOptionPane.QUESTION_MESSAGE);
        // Si el usuario cancela el diálogo → salir del método
        
        if (ciudadStr == null) {
            return;
        }
            try {
                int respuesta = JOptionPane.showConfirmDialog(this,
                "¿Estás seguro de eliminar la visita programada hacia " + ciudadStr + "?",
                "Confirmar eliminación",JOptionPane.YES_NO_OPTION);
                
        if (respuesta == JOptionPane.YES_OPTION) {
            boolean eliminado = LogicaRegistro.eliminarRegistroPorCiudad(ciudadStr);
            if (eliminado) {
            JOptionPane.showMessageDialog(this,
            "De acuerdo, eliminamos la visita a la ciudad " + ciudadStr + " en la estacion ",
            "Fin del proceso",JOptionPane.INFORMATION_MESSAGE);
            
            refrescarTabla(); // Actualiza la tabla
            break; // Salir del bucle tras eliminar
        } else {
                JOptionPane.showMessageDialog(this,
                "No se encontró ninguna visita con destino a: " + ciudadStr,
                "No encontrado", JOptionPane.ERROR_MESSAGE);
        // Repetir el bucle para dar otra oportunidad
        }
        } else {
                JOptionPane.showMessageDialog(this,"Sabia que no te querías perder la visita a la ciudad " + ciudadStr + "en la fecha ",
                "Cancelado",JOptionPane.INFORMATION_MESSAGE);
                break; // Salir si el usuario cancela
        }
        }catch(NumberFormatException e){
            
        }
    }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
         try {
        UIManager.LookAndFeelInfo lookAndFeel = UIManager.getInstalledLookAndFeels()[jComboBox1.getSelectedIndex()];
        UIManager.setLookAndFeel(lookAndFeel.getClassName());
        SwingUtilities.updateComponentTreeUI(this);
        this.pack();
    } catch (Exception e) {
        e.printStackTrace();
    }    
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtonAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAyudaActionPerformed
        ayuda.mostrarAyuda();
    }//GEN-LAST:event_jButtonAyudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PlanificadorViajes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAyuda;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCiudad;
    private javax.swing.JMenuItem jMenuItemTemperatura;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRegistros;
    // End of variables declaration//GEN-END:variables
}
