/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import dto.Registro;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import logica.LogicaRegistro;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;

/**
 *
 * @author Juanma
 */
public class RegistroTemperaturas extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroTemperaturas.class.getName());

    /**
     * Creates new form RegistroTemperaturas
     */
    public RegistroTemperaturas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //Desactivamos el botón "Registrar" por defecto
        jButtonRegistrarTemp.setEnabled(false);
        // Creamos el grupo de validación del ValidationPanel
        ValidationGroup group = validationPanelTemp.getValidationGroup();
        
        // Ciudad no vacía y solo letras y espacios
        group.add(jTextFieldMinima,
        StringValidators.REQUIRE_VALID_INTEGER,
        StringValidators.REQUIRE_VALID_INTEGER);
        
        
        
        // Activar o desactivar el botón según la validez
        validationPanelTemp.addChangeListener(e -> {
        jButtonRegistrarTemp.setEnabled(validationPanelTemp.getProblem() == null);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerMaxima = new javax.swing.JSpinner();
        jTextFieldMinima = new javax.swing.JTextField();
        validationPanelTemp = new org.netbeans.validation.api.ui.swing.ValidationPanel();
        jButtonRegistrarTemp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Temperatura mínima prevista (ºC):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 23, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Temperatura máxima prevista (ºC):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 23, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 89;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 62, 0, 0);
        jPanel1.add(jSpinnerMaxima, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 89;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 62, 0, 0);
        jPanel1.add(jTextFieldMinima, gridBagConstraints);

        jButtonRegistrarTemp.setText("Registrar");
        jButtonRegistrarTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarTempActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonRegistrarTemp)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(validationPanelTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(validationPanelTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jButtonRegistrarTemp)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegistrarTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarTempActionPerformed
        try {
        // Parsear valores double
        double tempMin = Double.parseDouble(jTextFieldMinima.getText());
        double tempMax = ((Number) jSpinnerMaxima.getValue()).doubleValue();

        // Validación: mínima no puede ser mayor que máxima
        if (tempMin > tempMax) {
            JOptionPane.showMessageDialog(this, 
                "La temperatura mínima no puede ser mayor que la máxima", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        double tempProm = (tempMin + tempMax) / 2.0;

        // Obtener el último registro añadido (ciudad + fecha)
        List<Registro> lista = LogicaRegistro.getRegistrosDirecto();
        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "No hay registro previo. Primero introduce ciudad y fecha.",
                "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Registro ultimo = lista.get(lista.size() - 1); // Último registro

        // Modificarlo
        ultimo.setTempMin(tempMin);
        ultimo.setTempMax(tempMax);
        ultimo.setTempProm(tempProm);

        // Refrescar tabla si el padre es PlanificadorViajes
        if (getParent() instanceof PlanificadorViajes) {
            ((PlanificadorViajes) getParent()).refrescarTabla();
        }

        this.dispose();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, 
            "Introduce valores numéricos válidos", 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButtonRegistrarTempActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                RegistroTemperaturas dialog = new RegistroTemperaturas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistrarTemp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerMaxima;
    private javax.swing.JTextField jTextFieldMinima;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanelTemp;
    // End of variables declaration//GEN-END:variables
}
